-- ============================================================================
-- PROJECT: InnerWhispers AI Wellness Companion
-- MODULE: Database Schema Draft (Sprint 1, Day 1)
-- DESCRIPTION: Draft schema definition covering users, mood_entries, 
--              journal_entries, chat_sessions, chat_messages, assessments, 
--              support_requests, crisis_flags, wellness_resources, and 
--              resource_embeddings tables.
-- ============================================================================

-- 1. Enable Required PostgreSQL Extensions
-- pgvector is required for RAG (Retrieval-Augmented Generation) based vector embeddings
CREATE EXTENSION IF NOT EXISTS vector;
-- uuid-ossp is required for generating UUIDs automatically
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Clean Existing Tables (For Development & Reset Purposes)
DROP TABLE IF EXISTS resource_embeddings CASCADE;
DROP TABLE IF EXISTS wellness_resources CASCADE;
DROP TABLE IF EXISTS crisis_flags CASCADE;
DROP TABLE IF EXISTS support_requests CASCADE;
DROP TABLE IF EXISTS assessment_responses CASCADE;
DROP TABLE IF EXISTS assessment_submissions CASCADE;
DROP TABLE IF EXISTS assessments CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS chat_sessions CASCADE;
DROP TABLE IF EXISTS journal_entries CASCADE;
DROP TABLE IF EXISTS mood_entries CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 3. Table: users
-- Represents the application profile linked to Supabase Auth.
CREATE TABLE users (
    id UUID PRIMARY KEY, -- Match UUID from auth.users (Supabase Auth)
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'user' CHECK (role IN ('user', 'admin', 'counselor')),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE users IS 'User profiles mirroring and extending Supabase Auth accounts.';

-- 4. Table: mood_entries (Unified Design)
-- Captures quantitative wellness markers and qualitative reflections.
CREATE TABLE mood_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mood TEXT NOT NULL, -- e.g., 'Anxious', 'Productive', 'Sad', 'Calm'
    mood_score INT NOT NULL CHECK (mood_score >= 1 AND mood_score <= 10),
    stress_level INT NOT NULL CHECK (stress_level >= 1 AND stress_level <= 10),
    sleep_quality INT NOT NULL CHECK (sleep_quality >= 1 AND sleep_quality <= 10),
    energy_level INT NOT NULL CHECK (energy_level >= 1 AND energy_level <= 10),
    note TEXT, -- Optional text notes reflecting details
    tags TEXT[] DEFAULT '{}'::TEXT[], -- e.g., ['exams', 'peer-pressure']
    recorded_at TIMESTAMPTZ DEFAULT NOW() NOT NULL, -- Logical event time
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL  -- Physical creation time
);

COMMENT ON TABLE mood_entries IS 'Granular mood tracking entries capturing multiple state dimensions.';

-- 5. Table: journal_entries
-- Private reflective texts with metadata parsed via AI.
CREATE TABLE journal_entries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    ai_summary TEXT, -- Extracted AI summary of journal text
    emotion_tags TEXT[] DEFAULT '{}'::TEXT[], -- Sentiment emotions tags generated by AI
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE journal_entries IS 'Private user journal logs with AI-generated semantic tags and summaries.';

-- 6. Table: chat_sessions
-- Tracks conversations users have with the AI wellness companion.
CREATE TABLE chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    risk_level TEXT DEFAULT 'low' CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE chat_sessions IS 'Active or historic conversations with the AI wellness companion.';

-- 7. Table: chat_messages
-- Houses the individual exchanges of a chat session.
CREATE TABLE chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    sender TEXT NOT NULL CHECK (sender IN ('user', 'assistant')),
    message TEXT NOT NULL,
    risk_flag BOOLEAN DEFAULT FALSE NOT NULL, -- True if content flags safety filters
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE chat_messages IS 'Message history inside chat sessions with safety risk markers.';

-- 8. Table: assessments
-- Configuration definitions of standardized clinical quizzes (e.g., PHQ-9, GAD-7)
CREATE TABLE assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL UNIQUE, -- e.g., 'PHQ-9 (Depression Screening)', 'GAD-7 (Anxiety Test)'
    description TEXT NOT NULL,
    questions JSONB NOT NULL, -- Array of questions, options, and weight scores
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE assessments IS 'Standardized wellness assessment metadata and configurations.';

-- 9. Table: assessment_submissions
-- Captures results when a user finishes a quiz.
CREATE TABLE assessment_submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assessment_id UUID NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
    score INT NOT NULL, -- Total score computed
    severity TEXT NOT NULL, -- Derived bracket (e.g. 'Mild', 'Moderate', 'Severe')
    answers JSONB NOT NULL, -- Map of Question ID -> Selected Answer Index/Value
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE assessment_submissions IS 'Historic records of user answers and derived clinical scores.';

-- 10. Table: support_requests
-- Bridges the user to campus counselors when high stress or escalation is requested.
CREATE TABLE support_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    request_type TEXT NOT NULL CHECK (request_type IN ('general', 'counseling', 'academic_anxiety', 'crisis')),
    priority TEXT DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'resolved')),
    user_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE support_requests IS 'Tickets created by students seeking human campus counseling support.';

-- 11. Table: crisis_flags
-- Automated records when an AI engine/system flags risk content.
CREATE TABLE crisis_flags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    detected_risk TEXT NOT NULL, -- e.g., 'self-harm ideation', 'severe depressive pattern'
    source TEXT NOT NULL CHECK (source IN ('chat', 'journal', 'assessment')),
    action_taken TEXT NOT NULL, -- e.g., 'crisis_hotline_shown', 'counselor_notified'
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'reviewed', 'closed')),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE crisis_flags IS 'Safety indicators triggered by NLP algorithms that demand rapid review.';

-- 12. Table: wellness_resources
-- Ground truth informational content for the student body.
CREATE TABLE wellness_resources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    category TEXT NOT NULL, -- e.g., 'Anxiety', 'Time Management', 'Sleep'
    content TEXT NOT NULL,
    external_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE wellness_resources IS 'Vetted mental wellness resources serving as context for RAG.';

-- 13. Table: resource_embeddings
-- Stores vectorized chunks of the wellness resources for similarity lookup.
CREATE TABLE resource_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    resource_id UUID NOT NULL REFERENCES wellness_resources(id) ON DELETE CASCADE,
    chunk_text TEXT NOT NULL,
    embedding VECTOR(1536) NOT NULL, -- Vector size suited for Gemini Embeddings
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE resource_embeddings IS 'Vectorized resource chunks supporting semantic cosine similarity searches.';
